;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.

(load "shared.lisp")

(defun fib-memo (base target memo)
  (cond ((= target 1) 1)
        ((= target 2) 1)
        (t (let ((fib-num (+ (car memo) (car (cdr memo)))))
             (cond ((= base target) fib-num)
                   (t (fib-memo (+ base 1) target (cons fib-num memo))))))))

(defun fib (num)
  (fib-memo 3 num '(1 1)))

(defun fib-sequence (base max-val acc)
  (let ((term (fib base)))
    (cond ((>= term max-val) acc)
          ((= (mod term 2) 0) (fib-sequence (+ base 1) max-val (cons term acc)))
          (t (fib-sequence (+ base 1) max-val acc)))))

(defun sum-fibs (max-val)
  (sum (fib-sequence 1 max-val '())))

(format t "~d~%" (sum-fibs 4000000))
